### PR TITLE
feat: MSK serverless cluster

### PR DESCRIPTION
**Pull request by magreenbaum**
## Description
Add msk serverless cluster. 

## Motivation and Context
https://docs.aws.amazon.com/msk/latest/developerguide/serverless.html

## Breaking Changes
No.

## How Has This Been Tested?
- [x] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by magreenbaum** [comment]
Unstale

**Comment by bryantbiggs** [comment]
whoops - I think we want to put this in its own sub-module similar to the other serverless offerings (RedShift, OpenSearch, etc)

**Review by bryantbiggs — APPROVED** [review]
awesome, thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 2.6.0 :tada:

**Pull request merged**
